### ISSUE TITLE
Only works on saved files.

### ISSUE THREAD

**Issue by earthlingdavey** [knowbee/rona-vscode-extension#15]
Hi, I've just downloaded the plugin. Thanks - I'm sure it will save me a load of time 😀

It seems to only work on saved files, which was a bit confusing for a while.

Can I suggest you consider adding this to the docs?

MacOS & VSCode Version: 1.56.2

**Comment by knowbee** [comment]
Yeah sure..Thanks

**Comment by earthlingdavey** [comment]
I know it's something minor... but I don't mind to make a quick patch and submit a PR.

**Comment by knowbee** [comment]
Go for it
