### ISSUE TITLE
Problem with multi-line require statements

### ISSUE THREAD

**Issue by iPherian** [knowbee/rona-vscode-extension#7]
For a line like this:

```
const {
  thing,
  anotherThing,
  widget,
  shape,
  color,
} = require("module");
```

Nothing happens (require statements on one line are converted though)

Version:
v1.0.2
in vscode

**Comment by knowbee** [comment]
This is would be a nice feature to add. I will work on it

**Comment by iPherian** [comment]
Thanks for the really quick fix!

Unfortunately, I noticed a few problems with the new version:

#### - Multi-line requires have quotes stripped incorrectly:

```
const {
  thing,
  anotherThing,
  widget,
  shape,
  color,
} = require("module");
```

produces:

```
 import {
  thing,
  anotherThing,
  widget,
  shape,
  color,
} from module
```

expected: quotes around the module name

#### - Multi-line requires with an '@' symbol don't work:

```
const {
  thing,
  anotherThing,
  widget,
  shape,
  color,
} = require("@org/module");
```

produces: no change

expected: convert to import

single line requires with an @ symbol work correctly

----------------------------------------------------------------

version:
1.0.4
vscode

**Comment by iPherian** [comment]
Also:

#### - Problem of multi-line requires with aliases:

```
const {
  thing,
  anotherThing,
  widget: renamedWidget,
  shape,
  color,
} = require("module");
```

produces:

```
const {
  thing,
  anotherThing,
  widget:
 import renamedWidget,
  shape,
  color,
} from module
```

expected:

```
import {
  thing,
  anotherThing,
  widget as renamedWidget,
  shape,
  color,
} from "module";
```

v1.0.4
vscode

**Comment by knowbee** [comment]
> Thanks for the really quick fix!
> 
> Unfortunately, I noticed a few problems with the new version:
> 
> #### - Multi-line requires have quotes stripped incorrectly:
> ```
> const {
>   thing,
>   anotherThing,
>   widget,
>   shape,
>   color,
> } = require("module");
> ```
> 
> produces:
> 
> ```
>  import {
>   thing,
>   anotherThing,
>   widget,
>   shape,
>   color,
> } from module
> ```
> 
> expected: quotes around the module name
> 
> #### - Multi-line requires with an '@' symbol don't work:
> ```
> const {
>   thing,
>   anotherThing,
>   widget,
>   shape,
>   color,
> } = require("@org/module");
> ```
> 
> produces: no change
> 
> expected: convert to import
> 
> single line requires with an @ symbol work correctly
> 
> version:
> 1.0.4
> vscode

this has been fixed

**Comment by knowbee** [comment]
> Also:
> 
> #### - Problem of multi-line requires with aliases:
> ```
> const {
>   thing,
>   anotherThing,
>   widget: renamedWidget,
>   shape,
>   color,
> } = require("module");
> ```
> 
> produces:
> 
> ```
> const {
>   thing,
>   anotherThing,
>   widget:
>  import renamedWidget,
>   shape,
>   color,
> } from module
> ```
> 
> expected:
> 
> ```
> import {
>   thing,
>   anotherThing,
>   widget as renamedWidget,
>   shape,
>   color,
> } from "module";
> ```
> 
> v1.0.4
> vscode

This has been fixed..update to version 1.0.5

**Comment by iPherian** [comment]
@knowbee it works in 1.0.5 -- thanks!
