### ISSUE TITLE
Non-require statements in a file being changed

### ISSUE THREAD

**Issue by iPherian** [knowbee/rona-vscode-extension#9]
this:

```
const { thing } = require("module");

function execute() {
    return {
        color: "green",
    };
}
```

produces:

```
import { thing } from "module"

function execute() {
    return {
        color as "green",
    };
}
```

expected: not to modify the unrelated statement below the require lines, the [ color: "green" ] line.

v1.0.5
vscode

**Comment by knowbee** [comment]
The trade-off would be to make sure you format the file to single-line require statements before you convert.

**Comment by iPherian** [comment]
hmm like remove everything except the require statements? I guess. Sure would be convenient if you could just use the file as is.

**Comment by knowbee** [comment]
I don't have much time to debug this, any help would be appreciated

**Comment by iPherian** [comment]
Oh I see what you mean, the new v1.0.6 fixes this issue but breaks multi-line requires. Yeah, I could probably spare some time to debug it.

**Comment by knowbee** [comment]
#11
